### PR TITLE
Add color redlines

### PR DESCRIPTION
**Pull request by kaiguo**
V1:

V2:

### CODE REVIEW

**Comment by chigy** [comment]
Very cool. BTW, is it possible to make the line not overlap the text? I am talking about here. Is there a way to guarantee text and line always avoid themselves somehow? (nice to have for v1 if hard :))

image

**Comment by chigy** [comment]
Can this be in red text and maybe inside a box?
image

**Comment by chigy** [comment]
Why are color names different between what's in redline and what's in the list of text?

image
image

**Comment by chigy** [comment]
BTW, none of the comment I made should stop submission. I can open issues if you want instead. :) Just didn't want to lose the feedback... Very cool!!!

**Comment by kaiguo** [comment]
> Very cool. BTW, is it possible to make the line not overlap the text? I am talking about here. Is there a way to guarantee text and line always avoid themselves somehow? (nice to have for v1 if hard :))
> 
> image

I think it's possible, i'll try fixing it : )

**Comment by kaiguo** [comment]
> Why are color names different between what's in redline and what's in the list of text?
> 
> image
> image

The names in the list are full names in generic.xaml. I stripped out "SystemControl" and "brush" parts in redline to make them shorter. But yeah, I can update the list to make those names consistent.

**Review by kaiguo — COMMENTED** [review]
@chigy made some changes to fix the issues. I've attached the latest screenshot in PR description.

**Review by chigy — APPROVED** [review]
Visuals look good and let's get that in. :)

**Pull request merged**
